language: ruby
rvm:
  - "2.0.0"
  - "2.1.5"
  - "2.2.0"
sudo:
  false

before_script:
  - wget https://cdn.crate.io/downloads/releases/crate-0.48.2.tar.gz -O /tmp/crate.tar.gz
  - tar -xvf /tmp/crate.tar.gz
  - bundle exec ruby spec/test_server.rb $PWD/crate-0.48.2/ true

script: bundle exec rspec spec
